# Generated by Django 5.1 on 2024-08-30 12:41

import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=11, unique=True, verbose_name="شماره موبایل"),
                ),
                ("email", models.EmailField(blank=True, max_length=100, verbose_name="ایمیل")),
                ("name", models.CharField(blank=True, max_length=50, verbose_name="نام")),
                (
                    "family",
                    models.CharField(blank=True, max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "register_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="تاریخ ثبت"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت ")),
                (
                    "active_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="کد فعال سازی"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "db_table": "A_CustomUser",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="آدرس")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتری ها ",
                "db_table": "A_Customers",
            },
        ),
        migrations.CreateModel(
            name="SalonManager",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="آدرس")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "salon_number",
                    models.IntegerField(blank=True, null=True, verbose_name="تلفن سالن"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "مدیر سالن",
                "verbose_name_plural": "مدیران سالن ها",
                "db_table": "A_Salon_Managers",
            },
        ),
        migrations.CreateModel(
            name="Stylist",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="توضیحات")),
                (
                    "linkedin_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک لینکدین"
                    ),
                ),
                (
                    "insta_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک اینستا"
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک تلگرام "
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="آدرس")),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "آرایشگر",
                "verbose_name_plural": "آرایشگران",
                "db_table": "ََA_Stylists",
            },
        ),
        migrations.CreateModel(
            name="WorkSamples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sample_title", models.CharField(max_length=100, verbose_name="عنوان نمونه کار")),
                (
                    "sample_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "stylist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_samples_of_stylist",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه کار",
                "verbose_name_plural": "نمونه کار ها",
                "db_table": "A_Work_Samples",
            },
        ),
    ]
