# Generated by Django 5.1 on 2024-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylist",
            name="expert",
            field=models.ManyToManyField(
                related_name="experts_of_stylist", to="services.services", verbose_name="تخصص"
            ),
        ),
    ]
