# Generated by Django 5.1 on 2024-09-14 15:35

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customer_profile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stylist",
            name="work_samles",
        ),
        migrations.AddField(
            model_name="worksamples",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_samples_of_stylist",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="salonmanager",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="stylist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="worksamples",
            name="sample_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
            ),
        ),
    ]
