# Generated by Django 5.1 on 2024-09-28 16:38

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_customer_profile_image_and_more"),
        ("services", "0013_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksamples",
            name="sample_title",
        ),
        migrations.AddField(
            model_name="worksamples",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_samples_services",
                to="services.services",
                verbose_name="خدمت ",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="salonmanager",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="stylist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="worksamples",
            name="sample_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
            ),
        ),
    ]
