# Generated by Django 5.1 on 2024-10-07 17:36

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_customer_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="salonmanager",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="stylist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="worksamples",
            name="sample_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
            ),
        ),
    ]
