# Generated by Django 5.1.4 on 2025-04-13 18:32

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_alter_customer_profile_image_and_more"),
        ("salons", "0066_alter_salon_banner_image_alter_salon_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="added_by_salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_customers",
                to="salons.salon",
                verbose_name="اضافه شده توسط سالن",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="salonmanager",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="stylist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="worksamples",
            name="sample_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
            ),
        ),
    ]
