# Generated by Django 5.1.4 on 2025-08-17 17:56

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_alter_customer_profile_image_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.A user will get all permissions granted to each of their groups.",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="salonmanager",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="stylist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="worksamples",
            name="sample_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر نمونه کار"
            ),
        ),
    ]
