# Generated by Django 5.1 on 2024-08-30 12:41

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("feature_name", models.CharField(max_length=100, verbose_name="نام ویژگی ")),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی ها",
                "db_table": "s_feature",
            },
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_title", models.CharField(max_length=100, verbose_name="عنوان مقدار")),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_values",
                        to="services.feature",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی ها ",
            },
        ),
        migrations.CreateModel(
            name="GroupServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("group_title", models.CharField(max_length=50, verbose_name="عنوان گروه خدمات ")),
                (
                    "group_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات گروه خدمات "),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/ غیرفعال"
                    ),
                ),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار "
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="زمان آخرین ویرایش"),
                ),
                ("slug", models.SlugField(max_length=200, null=True)),
                (
                    "group_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="services.groupservices",
                        verbose_name="والد گروه خدمات",
                    ),
                ),
            ],
            options={
                "verbose_name": "گروه خدمات",
                "verbose_name_plural": "گروه های خدمات ",
                "db_table": "s_groupservices",
            },
        ),
        migrations.AddField(
            model_name="feature",
            name="product_group",
            field=models.ManyToManyField(
                related_name="features_of_groups",
                to="services.groupservices",
                verbose_name="گروه خدمات",
            ),
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="مقدار")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.feature",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "filter_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.featurevalue",
                        verbose_name="مقدار فیلتر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی خدمات",
                "verbose_name_plural": "ویژگی های خدمات",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_name", models.CharField(max_length=500, verbose_name="نام خدمات")),
                (
                    "summery_description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="توضیحات خلاصه خدمات"
                    ),
                ),
                ("description", ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                (
                    "service_image",
                    models.ImageField(
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر خدمات",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="قیمت خدمات")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="وضعیت فعال / غیرفعال"
                    ),
                ),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="زمان آخرین ویرایش"),
                ),
                ("slug", models.SlugField(max_length=200, null=True, verbose_name="اسلاگ")),
                (
                    "features",
                    models.ManyToManyField(
                        through="services.ServiceFeature", to="services.feature"
                    ),
                ),
                (
                    "service_group",
                    models.ManyToManyField(
                        related_name="services_of_group",
                        to="services.groupservices",
                        verbose_name="گروه خدمات",
                    ),
                ),
                (
                    "stylists",
                    models.ManyToManyField(
                        related_name="services_of_stylist",
                        to="accounts.stylist",
                        verbose_name="آرایشگران",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمات",
                "verbose_name_plural": "خدمات",
                "db_table": "s_services",
            },
        ),
        migrations.CreateModel(
            name="ServiceGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="services.services",
                        verbose_name="خدمات",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر خدمات",
                "verbose_name_plural": "تصاویر خدمات",
            },
        ),
        migrations.AddField(
            model_name="servicefeature",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_features",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
    ]
