# Generated by Django 5.1 on 2024-08-30 13:38

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="product_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
