# Generated by Django 5.1 on 2024-09-01 16:31

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="product_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
