# Generated by Django 5.1 on 2024-09-27 16:21

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_customer_profile_image_and_more"),
        ("services", "0011_remove_services_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="product_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="stylist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stylist_prices",
                to="accounts.stylist",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
