# Generated by Django 5.1 on 2024-10-07 17:36

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicegallery",
            name="product",
        ),
        migrations.RemoveField(
            model_name="servicegallery",
            name="product_image",
        ),
        migrations.AddField(
            model_name="servicegallery",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.AddField(
            model_name="servicegallery",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
