# Generated by Django 5.1 on 2024-10-17 20:09

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_customer_profile_image_and_more"),
        ("services", "0024_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprice",
            unique_together={("service", "stylist")},
        ),
    ]
