# Generated by Django 5.1 on 2024-10-19 18:30

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_services_duration_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="duration",
        ),
        migrations.AddField(
            model_name="services",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30, verbose_name="مدت زمان خدمت (دقیقه)"),
        ),
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
