# Generated by Django 5.1.4 on 2025-02-11 16:09

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0052_remove_groupservices_slug_remove_services_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupservices",
            name="group_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر گروه خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="servicegallery",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات کامل خدمات"),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                null=True, upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر خدمات"
            ),
        ),
    ]
