# Generated by Django 5.1 on 2024-08-30 12:41

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="عنوان"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدرها",
                "db_table": "M_slider",
            },
        ),
    ]
