# Generated by Django 5.1 on 2024-08-31 20:13

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
