# Generated by Django 5.1 on 2024-10-11 15:34

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_slider_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="descriptions",
            field=models.TextField(null=True, verbose_name="توضیحات "),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
