# Generated by Django 5.1.4 on 2025-01-11 19:22

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0059_alter_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
