# Generated by Django 5.1.4 on 2025-04-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_alter_slider_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Slider",
        ),
    ]
