# Generated by Django 5.1.4 on 2025-02-08 18:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_alter_customer_profile_image_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChosenAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="آدرس"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="موقعیت"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس انتخابی",
                "verbose_name_plural": "آدرس های انتخابی",
                "db_table": "ChosenAddress",
            },
        ),
    ]
