from django.urls import path

from .views import (
    SalonManagerDashboardView,
    salonManagerHeader,
    DashboardHomeView,
    recently_sales,
    upcoming_appointments,
    get_popular_services,
    today_appointment,
    appointments_activity,
    SalonsCustomersPageView,
    OnlineBookingView,
    salon_profile_creator,
    SalonProfileCreatorStep1View,
    SalonProfileCreatorStep2View,
    SalonProfileCreatorStep3View,
    salon_profile_creator_step4,
    salon_profile_creator_step5,
    SalonProfileCreatorStep6View,
    delete_salon_image,
    SalonProfileCreatorStep7View,
    SalonProfileCreatorStep8View,
    salon_profile_creator_step9,
    SalonProfileCreatorStep10View,
    salon_profile_creator_finalStep,
    SalonProfileView,
    CatalogView,
    ServiceMenuView,
    AddServicesView,
    EditServiceView,
    archieve_service,
    remove_service,
    membership,
    products,
    stocktakes,
    team_managment,
    TeamMemberView,
    StylistOverviewView,
    AddStylistView,
    EditStylistView,
    get_services_list,
    ScheduledShiftsView,
    EditStylistDayScheduleView,
    DeleteDayScheduleView,
    SetRegularShiftsView,
    AddTimeOffView,
    get_popular_stylists,
    calendar_view,
    get_calendar_data,
    mark_appointment_paid,
    create_appointment,
    update_appointment,
    cancel_appointment,
)

# ----------------------------------------------------------------
app_name = "dashboards"
urlpatterns = [
    path(
        "",
        SalonManagerDashboardView.as_view(),
        name="salon_manager_dashboard",
    ),
    path("salonManagerHeader/", salonManagerHeader, name="salon_manager_header"),
    path("home/", DashboardHomeView.as_view(), name="home"),
    path("recently-sales/", recently_sales, name="recentlySales"),
    path(
        "upcoming-appointments/",
        upcoming_appointments,
        name="upcomingAppointments",
    ),
    path("popular_services/", get_popular_services, name="popular_services"),
    path("popular_stylists/", get_popular_stylists, name="popular_stylists"),
    path("today_appointments/", today_appointment, name="today_appointments"),
    path("appointments_activity/", appointments_activity, name="appointments_activity"),
    path(
        "SalonsCustomers/",
        SalonsCustomersPageView.as_view(),
        name="salons_customers_page",
    ),
    path("online_booking/", OnlineBookingView.as_view(), name="online_booking"),
    path("salon_profile_creator/", salon_profile_creator, name="salon_profile_creator"),
    path(
        "salon_profile_creator_step1/",
        SalonProfileCreatorStep1View.as_view(),
        name="salon_profile_creator_step1",
    ),
    path(
        "salon_profile_creator_step2/",
        SalonProfileCreatorStep2View.as_view(),
        name="salon_profile_creator_step2",
    ),
    path(
        "salon_profile_creator_step3/",
        SalonProfileCreatorStep3View.as_view(),
        name="salon_profile_creator_step3",
    ),
    path(
        "salon_profile_creator_step4/",
        salon_profile_creator_step4,
        name="salon_profile_creator_step4",
    ),
    path(
        "salon_profile_creator_step5/",
        salon_profile_creator_step5,
        name="salon_profile_creator_step5",
    ),
    path(
        "salon_profile_creator_step6/",
        SalonProfileCreatorStep6View.as_view(),
        name="salon_profile_creator_step6",
    ),
    path(
        "salon/gallery/delete/<int:image_id>/",
        delete_salon_image,
        name="delete_salon_image",
    ),
    path(
        "salon_profile_creator_step7/",
        SalonProfileCreatorStep7View.as_view(),
        name="salon_profile_creator_step7",
    ),
    path(
        "salon_profile_creator_step8/",
        SalonProfileCreatorStep8View.as_view(),
        name="salon_profile_creator_step8",
    ),
    path(
        "salon_profile_creator_step9/",
        salon_profile_creator_step9,
        name="salon_profile_creator_step9",
    ),
    path(
        "salon_profile_creator_step10/",
        SalonProfileCreatorStep10View.as_view(),
        name="salon_profile_creator_step10",
    ),
    path(
        "salon_profile_creator_finalStep/",
        salon_profile_creator_finalStep,
        name="salon_profile_creator_finalStep",
    ),
    path("salon_profile/", SalonProfileView.as_view(), name="salon_profile"),
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("service_menu/", ServiceMenuView.as_view(), name="service_menu"),
    path("add_service/", AddServicesView.as_view(), name="add_service"),
    path("edit_service/<int:service_id>/", EditServiceView.as_view(), name="edit_service"),
    path("archieve_service/<int:service_id>/", archieve_service, name="archieve_service"),
    path("remove_service/<int:service_id>/", remove_service, name="remove_service"),
    path("membership/", membership, name="membership"),
    path("products/", products, name="products"),
    path("stocktakes/", stocktakes, name="stocktakes"),
    path("team_managment/", team_managment, name="team_managment"),
    path("team_member/", TeamMemberView.as_view(), name="team_member"),
    path(
        "stylist_overview/<int:stylist_id>/",
        StylistOverviewView.as_view(),
        name="stylist_overview",
    ),
    path("add_stylist/", AddStylistView.as_view(), name="add_stylist"),
    path("edit_stylist/<int:stylist_id>/", EditStylistView.as_view(), name="edit_stylist"),
    path("api/services/", get_services_list, name="services_list"),
    path("scheduled_shifts/", ScheduledShiftsView.as_view(), name="scheduled_shifts"),
    path(
        "schedule/edit-day/stylist/<int:stylist_pk>/salon/<int:salon_pk>/date/<str:date_iso>/",
        EditStylistDayScheduleView.as_view(),
        name="edit_day_schedule",
    ),
    path(
        "schedule/delete-day/stylist/<int:stylist_id>/date/<str:date_iso>/",
        DeleteDayScheduleView.as_view(),
        name="delete_day_schedule",
    ),
    path(
        "schedule/set-regular/stylist/<int:stylist_id>/salon/<int:salon_id>/",
        SetRegularShiftsView.as_view(),
        name="set_regular_shifts",
    ),
    path(
        "schedule/add-time-off/stylist/<int:stylist_id>/date/<str:date_iso>/salon/<int:salon_id>/",
        AddTimeOffView.as_view(),
        name="add_time_off",
    ),
    path("salon/<int:salon_id>/calendar/", calendar_view, name="appointment_calendar"),
    # API برای دریافت اطلاعات تقویم
    path(
        "api/calendar-data/salon/<int:salon_id>/",
        get_calendar_data,
        name="get_calendar_data",
    ),
    # API برای ایجاد نوبت جدید
    path(
        "api/salon/<int:salon_id>/appointments/",
        create_appointment,
        name="create_appointment",
    ),
    # API برای به‌روزرسانی نوبت
    path(
        "api/salon/<int:salon_id>/appointments/<int:appointment_id>/",
        update_appointment,
        name="update_appointment",
    ),
    # API برای لغو نوبت
    path(
        "api/salon/<int:salon_id>/appointments/<int:appointment_id>/cancel/",
        cancel_appointment,
        name="cancel_appointment",
    ),
    # API برای علامت‌گذاری پرداخت
    path(
        "api/salon/<int:salon_id>/appointments/<int:appointment_id>/mark-paid/",
        mark_appointment_paid,
        name="mark_appointment_paid",
    ),
]
