# Generated by Django 5.1 on 2024-11-01 18:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0044_alter_customer_profile_image_and_more"),
        ("salons", "0047_alter_salon_banner_image_alter_salon_video_and_more"),
        ("services", "0036_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payment_title", models.CharField(max_length=50, verbose_name="نوع پرداخت")),
            ],
            options={
                "verbose_name": "نوع پرداخت",
                "verbose_name_plural": "انواغ روش پرداخت",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "register_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="تاریخ ثبت"),
                ),
                ("update_date", models.DateField(auto_now=True, verbose_name="تاریخ آپدیت")),
                ("is_finally", models.BooleanField(default=False, verbose_name="نهایی شده")),
                (
                    "order_code",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="کد سفارش"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, default=0, null=True, verbose_name="تخفیف"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="توضیحات")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.paymenttype",
                        verbose_name="نوع پرداخت",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش ها",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.IntegerField(verbose_name=" قیمت")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details1",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details_salon",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details_services",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details_stylist",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
        ),
    ]
