# Generated by Django 5.1 on 2024-11-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="date",
            field=models.DateField(null=True, verbose_name="تاریخ"),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="time",
            field=models.TimeField(null=True, verbose_name="زمان"),
        ),
    ]
