# Generated by Django 5.1 on 2024-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderdetail_date_orderdetail_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stylist_approved",
            field=models.BooleanField(default=False, verbose_name="تایید آرایشگر"),
        ),
    ]
