# Generated by Django 5.1.4 on 2025-09-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_stylist_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="پرداخت شده"),
        ),
    ]
