# Generated by Django 5.1.4 on 2025-09-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name="مبلغ پرداخت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="شناسه پرداخت"
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="موجودی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول\u200cها",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "واریز"),
                            ("WITHDRAW", "برداشت"),
                            ("PURCHASE", "خرید"),
                            ("REFUND", "بازگشت وجه"),
                        ],
                        max_length=10,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, max_digits=10, verbose_name="مبلغ"),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="موجودی کیف پول بعد از انجام این تراکنش",
                        max_digits=10,
                        verbose_name="موجودی پس از تراکنش",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.wallet",
                        verbose_name="کیف پول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش کیف پول",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)), name="balance_gte_zero"
            ),
        ),
    ]
