# Generated by Django 5.1.4 on 2025-09-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_is_paid"),
        ("payments", "0002_alter_payment_amount_alter_payment_ref_id_wallet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_order",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
    ]
