# Generated by Django 5.1 on 2024-10-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0036_alter_customer_profile_image_and_more"),
        ("salons", "0039_alter_salon_banner_image_alter_salon_video_and_more"),
        ("services", "0028_services_duration_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StylistTimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ تعطیلی")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان شروع تعطیلی"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان پایان تعطیلی"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="دلیل"),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_offs",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعطیلی آرایشگر",
                "verbose_name_plural": "تعطیلی\u200cهای آرایشگر",
                "unique_together": {("stylist", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="StylistWeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "شنبه"),
                            (1, "یکشنبه"),
                            (2, "دوشنبه"),
                            (3, "سه\u200cشنبه"),
                            (4, "چهارشنبه"),
                            (5, "پنج\u200cشنبه"),
                            (6, "جمعه"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_weekly_schedules",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_weekly_schedules",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_weekly_schedules",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه هفتگی آرایشگر",
                "verbose_name_plural": "برنامه\u200cهای هفتگی آرایشگران",
                "unique_together": {("stylist", "day_of_week", "start_time", "service")},
            },
        ),
    ]
