# Generated by Django 5.1 on 2024-10-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_alter_customer_profile_image_and_more"),
        ("salons", "0045_alter_salon_banner_image_alter_salon_video_and_more"),
        ("services", "0034_alter_groupservices_group_image_and_more"),
        ("stylists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StylistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ ")),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_schedules",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_schedules",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_schedules",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه آرایشگر",
                "verbose_name_plural": "برنامه\u200cهای آرایشگران",
                "unique_together": {("stylist", "date", "start_time", "service")},
            },
        ),
        migrations.DeleteModel(
            name="StylistWeeklySchedule",
        ),
    ]
