# Generated by Django 5.1 on 2024-11-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_alter_customer_profile_image_and_more"),
        ("stylists", "0002_stylistschedule_delete_stylistweeklyschedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stylistschedule",
            unique_together={("stylist", "date", "start_time")},
        ),
    ]
