# Generated by Django 5.1.4 on 2025-05-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_stylist_calendar_color_alter_customer_profile_image_and_more"),
        ("salons", "0076_alter_customernote_note_image_and_more"),
        ("stylists", "0003_alter_stylistschedule_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="emergencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(max_length=255, verbose_name="شماره تماس اضطراری"),
                ),
                ("relationship", models.CharField(max_length=255, verbose_name="نسبت با آرایشگر")),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_info",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات اضطراری",
                "verbose_name_plural": "اطلاعات اضطراری",
            },
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True, verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(auto_now=True, verbose_name="تاریخ پایان")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_job_details",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_details",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزئیات شغلی",
                "verbose_name_plural": "جزئیات شغلی",
            },
        ),
    ]
