# Generated by Django 5.1.4 on 2025-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stylists", "0004_emergencyinfo_jobdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdetails",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="start_date",
            field=models.DateField(verbose_name="تاریخ شروع"),
        ),
    ]
