# Generated by Django 5.1.4 on 2025-05-16 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stylists", "0005_alter_jobdetails_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdetails",
            name="employment_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نوع استخدام"
            ),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="end_date",
            field=models.DateField(verbose_name="تاریخ پایان"),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="تاریخ شروع"),
        ),
    ]
