# Generated by Django 5.1.4 on 2025-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stylists", "0006_jobdetails_employment_type_alter_jobdetails_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdetails",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
        ),
    ]
