# Generated by Django 5.1.4 on 2025-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stylists", "0007_alter_jobdetails_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyinfo",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام و نام خانوادگی  "
            ),
        ),
    ]
