# Generated by Django 5.1.4 on 2025-08-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0060_alter_groupservices_group_image_and_more"),
        ("stylists", "0008_emergencyinfo_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylistschedule",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_schedules",
                to="services.services",
                verbose_name="خدمت",
            ),
        ),
    ]
