# Generated by Django 5.1 on 2024-08-31 16:54

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blogsgallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsgallery",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
