# Generated by Django 5.1 on 2024-09-30 19:48

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0018_alter_blogs_image_alter_blogsgallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(
                default="images/Blogs/default.jfif",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="blogsgallery",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
