# Generated by Django 5.1.4 on 2025-01-10 16:43

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0054_alter_blogs_description_alter_blogs_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(
                default="images/Blogs/default.jfif",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="blogsgallery",
            name="image",
            field=models.ImageField(upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر"),
        ),
    ]
