# Generated by Django 5.1 on 2024-08-30 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("register_date", models.DateField(auto_now_add=True, verbose_name="زمان درج")),
                ("comment_text", models.TextField(null=True, verbose_name="متن")),
                (
                    "approved_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر تایید کننده",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_user",
                        to="accounts.customer",
                        verbose_name="کاربر نظر دهنده",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_salon",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_services",
                        to="services.services",
                        verbose_name="خدمات",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_stylist",
                        to="accounts.stylist",
                        verbose_name=" آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "db_table": "c_comments",
            },
        ),
        migrations.CreateModel(
            name="Favorits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("register_date", models.DateField(auto_now_add=True, verbose_name="زمان درج")),
                (
                    "favorite_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_salon",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_services",
                        to="services.services",
                        verbose_name="خدمات",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_stylist",
                        to="accounts.stylist",
                        verbose_name=" آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه مندی",
                "verbose_name_plural": "علاقه مندی ها ",
                "db_table": "c_favorits",
            },
        ),
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("register_date", models.DateField(auto_now_add=True, verbose_name="زمان درج")),
                (
                    "score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_salon",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "scoring_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="امتیازدهنده",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_services",
                        to="services.services",
                        verbose_name="خدمات",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_stylist",
                        to="accounts.stylist",
                        verbose_name=" آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیازات",
                "db_table": "c_scoring",
            },
        ),
    ]
