# Generated by Django 5.1 on 2024-08-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_profile_image_and_more"),
        ("comments_scores_favories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_user",
                to="accounts.customer",
                verbose_name="کاربر نظر دهنده",
            ),
        ),
    ]
