# Generated by Django 5.1 on 2024-08-31 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customer_profile_image_and_more"),
        ("comments_scores_favories", "0002_alter_comments_comment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="approved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر تایید کننده",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_text",
            field=models.TextField(blank=True, null=True, verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_user",
                to="accounts.customer",
                verbose_name="کاربر نظر دهنده",
            ),
        ),
    ]
