# Generated by Django 5.1 on 2024-12-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_customer_profile_image_and_more"),
        ("comments_scores_favories", "0004_worksamplelike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoring",
            name="scoring_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_user",
                to="accounts.customer",
                verbose_name="امتیازدهنده",
            ),
        ),
    ]
