# Generated by Django 5.1.4 on 2025-04-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments_scores_favories", "0005_alter_scoring_scoring_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoring",
            name="salon",
        ),
        migrations.RemoveField(
            model_name="scoring",
            name="scoring_user",
        ),
        migrations.RemoveField(
            model_name="scoring",
            name="service",
        ),
        migrations.RemoveField(
            model_name="scoring",
            name="stylist",
        ),
        migrations.AddField(
            model_name="scoring",
            name="comment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring",
                to="comments_scores_favories.comments",
                verbose_name="نظر مربوطه",
            ),
        ),
    ]
