# Generated by Django 5.1.4 on 2025-04-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_alter_customer_profile_image_and_more"),
        (
            "comments_scores_favories",
            "0006_remove_scoring_salon_remove_scoring_scoring_user_and_more",
        ),
        ("salons", "0062_alter_salon_banner_image_alter_salon_video_and_more"),
        ("services", "0054_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoring",
            name="salon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_salon",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="scoring_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_user",
                to="accounts.customer",
                verbose_name="امتیازدهنده",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_services",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_stylist",
                to="accounts.stylist",
                verbose_name=" آرایشگر",
            ),
        ),
    ]
