# Generated by Django 5.1.4 on 2025-09-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0077_alter_customer_profile_image_and_more"),
        (
            "comments_scores_favories",
            "0007_scoring_salon_scoring_scoring_user_scoring_service_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorits",
            name="favorite_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_user",
                to="accounts.customer",
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="worksamplelike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.customer"
            ),
        ),
    ]
