# Generated by Django 5.1 on 2024-08-30 12:41

import ckeditor_uploader.fields
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("salon_name", models.CharField(max_length=50, verbose_name="نام سالن")),
                (
                    "banner_image",
                    models.ImageField(
                        default="salons_banner.jpg",
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="بنر",
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="توضیحات "
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="ویدیو",
                    ),
                ),
                ("zone", models.PositiveIntegerField(verbose_name="منطقه ")),
                ("address", models.TextField(blank=True, null=True, verbose_name="آدرس")),
                (
                    "linkedin_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک لینکدین"
                    ),
                ),
                (
                    "insta_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک اینستا"
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="لینک تلگرام "
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت ")),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                ("slug", models.SlugField(max_length=200, null=True, verbose_name="اسلاگ")),
                (
                    "salon_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_manager",
                        to="accounts.salonmanager",
                        verbose_name="مدیر سالن ",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="services_of_salon",
                        to="services.services",
                        verbose_name="خدمات ",
                    ),
                ),
                (
                    "stylists",
                    models.ManyToManyField(
                        related_name="stylists_of_salon",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سالن",
                "verbose_name_plural": "سالن ها ",
                "db_table": "s_salon",
            },
        ),
        migrations.CreateModel(
            name="SalonsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "salon_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر سالن",
                "verbose_name_plural": "تصاویر سالن ها ",
                "db_table": "salons_gallery",
            },
        ),
    ]
