# Generated by Django 5.1.4 on 2025-01-11 19:22

import django.contrib.gis.db.models.fields
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0054_alter_salon_banner_image_alter_salon_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326, verbose_name="موقعیت جغرافیایی"
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
    ]
