# Generated by Django 5.1.4 on 2025-01-14 22:17

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0056_salon_neighborhood_alter_salon_banner_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salon",
            name="slug",
        ),
        migrations.AddField(
            model_name="salon",
            name="close_at",
            field=models.TimeField(null=True, verbose_name="پایان کار"),
        ),
        migrations.AddField(
            model_name="salon",
            name="open_at",
            field=models.TimeField(null=True, verbose_name="شروع به کار"),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
    ]
