# Generated by Django 5.1.4 on 2025-01-16 20:05

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0058_alter_salon_banner_image_alter_salon_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salon",
            name="close_at",
        ),
        migrations.RemoveField(
            model_name="salon",
            name="open_at",
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.CreateModel(
            name="SalonOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "شنبه"),
                            (2, "یکشنبه"),
                            (3, "دوشنبه"),
                            (4, "سه شنبه"),
                            (5, "چهارشنبه"),
                            (6, "پنج شنبه"),
                            (7, "جمعه"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True, verbose_name="ساعت شروع")),
                ("close_time", models.TimeField(blank=True, null=True, verbose_name="ساعت پایان")),
                ("is_closed", models.BooleanField(default=False, verbose_name="تعطیل")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="salons.salon",
                        verbose_name="سالن مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ساعت کاری سالن",
                "verbose_name_plural": "ساعت کاری سالن\u200cها",
                "db_table": "s_salon_opening_hours",
            },
        ),
    ]
