# Generated by Django 5.1.4 on 2025-04-02 13:36

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0060_alter_salon_banner_image_alter_salon_video_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.CreateModel(
            name="SalonVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ بازدید"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_visits",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید سالن",
                "verbose_name_plural": "بازدیدهای سالن",
                "db_table": "s_salon_visit",
                "unique_together": {("user", "salon")},
            },
        ),
    ]
