# Generated by Django 5.1.4 on 2025-04-07 16:26

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0062_alter_salon_banner_image_alter_salon_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.CreateModel(
            name="SupplementaryInfoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                ("description", models.CharField(max_length=200, verbose_name="توضیحات")),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر آیکون",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplementary_info_views",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات تکمیلی",
                "verbose_name_plural": "اطلاعات تکمیلی",
                "db_table": "s_salon_supplementary_info",
            },
        ),
    ]
