# Generated by Django 5.1.4 on 2025-04-16 17:39

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_alter_customer_profile_image_and_more"),
        ("salons", "0066_alter_salon_banner_image_alter_salon_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.AlterField(
            model_name="supplementaryinfoview",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر آیکون",
            ),
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.TextField(verbose_name="یادداشت")),
                (
                    "note_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader.upload_to,
                        verbose_name="تصویر یادداشت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_note_creator",
                        to="accounts.stylist",
                        verbose_name="ایجاد کننده",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notes",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت مشتری",
                "verbose_name_plural": "یادداشت\u200cهای مشتری",
                "db_table": "s_customer_note",
            },
        ),
    ]
