# Generated by Django 5.1.4 on 2025-04-17 14:57

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0069_alter_customernote_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customernote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_note_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد کننده",
            ),
        ),
        migrations.AlterField(
            model_name="customernote",
            name="note_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر یادداشت",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.AlterField(
            model_name="supplementaryinfoview",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر آیکون",
            ),
        ),
    ]
