# Generated by Django 5.1.4 on 2025-04-18 19:20

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0070_alter_customernote_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="phone_number",
            field=models.PositiveIntegerField(
                blank=True, max_length=11, null=True, verbose_name="شماره تلفن "
            ),
        ),
        migrations.AlterField(
            model_name="customernote",
            name="note_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر یادداشت",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                default="salons_banner.jpg",
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.AlterField(
            model_name="supplementaryinfoview",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر آیکون",
            ),
        ),
    ]
