# Generated by Django 5.1.4 on 2025-04-19 13:08

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_alter_customer_profile_image_and_more"),
        ("salons", "0072_alter_customernote_note_image_and_more"),
        ("services", "0056_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customernote",
            name="note_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر یادداشت",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                default="salons_banner.jpg",
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="phone_number",
            field=models.IntegerField(
                blank=True, max_length=11, null=True, verbose_name="شماره تلفن "
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="services",
            field=models.ManyToManyField(
                related_name="services_of_salon", to="services.services", verbose_name="خدمات "
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="stylists",
            field=models.ManyToManyField(
                related_name="stylists_of_salon", to="accounts.stylist", verbose_name="آرایشگر"
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.AlterField(
            model_name="supplementaryinfoview",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر آیکون",
            ),
        ),
    ]
