# Generated by Django 5.1.4 on 2025-08-17 17:56

import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0074_alter_customer_profile_image_alter_customuser_groups_and_more"),
        ("salons", "0077_alter_customernote_note_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customernote",
            name="note_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر یادداشت",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                default="salons_banner.jpg",
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="بنر",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="ویدیو",
            ),
        ),
        migrations.AlterField(
            model_name="salonsgallery",
            name="salon_image",
            field=models.ImageField(
                upload_to=utils.File_Uploader.upload_to, verbose_name="تصویر سالن"
            ),
        ),
        migrations.AlterField(
            model_name="supplementaryinfoview",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.File_Uploader.upload_to,
                verbose_name="تصویر آیکون",
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(fields=["customer", "salon"], name="customer_salon_note_idx"),
        ),
    ]
