# Generated by Django 5.1 on 2024-11-02 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0037_alter_groupservices_group_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("coupon_code", models.CharField(max_length=100, verbose_name="کد تخفیف ")),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کد های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("discount_title", models.CharField(max_length=100, verbose_name="عنوان تخفیف")),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "سبد تخفیف ",
                "verbose_name_plural": "سبدهای تخفیف ",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasketDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "discount_basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_basket_details1",
                        to="discounts.discountbasket",
                        verbose_name="سبد تخفیف",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_basket_details2",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزییات سبد تخفیف ",
            },
        ),
    ]
