# Generated by Django 5.1 on 2024-11-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_alter_customer_profile_image_and_more"),
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountbasketdetails",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_basket_details3",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
    ]
